### ISSUE TITLE
[HELP] Filtering by CAP

### ISSUE THREAD

**Issue by MarcoRavich** [mlocati/comuni-italiani#11]
Ciao Michele,
I've installed your cool library but didn't understand how to filter municipalities by Codice Avviamento Postale.

If this function/data is not present is possible to implement it in future versions ?

Thanks in advance !

nota: sono (e parlo) italiano eh...

**Comment by mlocati** [comment]
Questa libreria non fornisce i CAP dei comuni: i dati vengono da Situas e lì non sono pubblicati - vedi https://situas.istat.it/web/#/territorio/body?id=61

**Comment by MarcoRavich** [comment]
Ciao, scusami, non avevo notato.

Altra domanda: e se volessi invece filtrare i comuni in base al "VehicleCode" ?

Grazie ancora.

**Comment by mlocati** [comment]
Vedi https://github.com/mlocati/comuni-italiani/blob/1.3.1/src/Finder.php#L81

**Comment by MarcoRavich** [comment]
> Vedi https://github.com/mlocati/comuni-italiani/blob/1.3.1/src/Finder.php#L81
>
Non sono espertissimo ma sì, ho visto il sorgente...
...sostanzialmente a me servirebbe un "getMunicipalityByVehicleCode" oppure devo fare 2 passaggi: getProvinceByVehicleCode poi listMunicipalities ?

Grazie delle info, buona serata.

**Comment by mlocati** [comment]
```php
$finder->getProvinceByVehicleCode('...')->getMunicipalities();
```

**Comment by MarcoRavich** [comment]
Perfetto, grazie !
